name: laundry_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/services/
    - assets/add_item/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
