// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYbwpxE5uw_WOZKuA2HN4CexyXEnvUGAU',
    appId: '1:990132316337:web:135cef215657b051e31a90',
    messagingSenderId: '990132316337',
    projectId: 'laundry-management-49c9d',
    authDomain: 'laundry-management-49c9d.firebaseapp.com',
    storageBucket: 'laundry-management-49c9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtzO0fLBI5_A8fPdX7GUuQcVMzIAdwLFU',
    appId: '1:990132316337:android:57a00e525915c6fbe31a90',
    messagingSenderId: '990132316337',
    projectId: 'laundry-management-49c9d',
    storageBucket: 'laundry-management-49c9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8D6R9R-bAhydvdEm3fbPHawsVGxLKps',
    appId: '1:990132316337:ios:ec0a77bfe0cf354ae31a90',
    messagingSenderId: '990132316337',
    projectId: 'laundry-management-49c9d',
    storageBucket: 'laundry-management-49c9d.firebasestorage.app',
    iosBundleId: 'com.example.laundryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK8D6R9R-bAhydvdEm3fbPHawsVGxLKps',
    appId: '1:990132316337:ios:ec0a77bfe0cf354ae31a90',
    messagingSenderId: '990132316337',
    projectId: 'laundry-management-49c9d',
    storageBucket: 'laundry-management-49c9d.firebasestorage.app',
    iosBundleId: 'com.example.laundryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYbwpxE5uw_WOZKuA2HN4CexyXEnvUGAU',
    appId: '1:990132316337:web:b06ea3e64244a988e31a90',
    messagingSenderId: '990132316337',
    projectId: 'laundry-management-49c9d',
    authDomain: 'laundry-management-49c9d.firebaseapp.com',
    storageBucket: 'laundry-management-49c9d.firebasestorage.app',
  );
}
